services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Con esto enlazamos el sistema de archivos a la instancia de docker.
    ports:
      - '80:80'